namespace BACnetAPA
{
    public enum BacnetDataTypes
    {
        BacnetApplicationTagNull = 0,
        BacnetApplicationTagBoolean = 1,
        BacnetApplicationTagUnsignedInt = 2,
        BacnetApplicationTagSignedInt = 3,
        BacnetApplicationTagReal = 4,
        BacnetApplicationTagDouble = 5,
        BacnetApplicationTagOctetString = 6,
        BacnetApplicationTagCharacterString = 7,
        BacnetApplicationTagBitString = 8,
        BacnetApplicationTagEnumerated = 9,
        BacnetApplicationTagDate = 10,
        BacnetApplicationTagTime = 11,
        BacnetApplicationTagObjectId = 12,
        BacnetApplicationTagReserve1 = 13,
        BacnetApplicationTagReserve2 = 14,
        BacnetApplicationTagReserve3 = 15,
        MaxBacnetApplicationTag = 16,
        BacnetApplicationTagEmptylist = 17,
        BacnetApplicationTagWeeknday = 18,
        BacnetApplicationTagDaterange = 19,
        BacnetApplicationTagDatetime = 20,
        BacnetApplicationTagTimestamp = 21,
        BacnetApplicationTagError = 22,
        BacnetApplicationTagDeviceObjectPropertyReference = 23,
        BacnetApplicationTagDeviceObjectReference = 24,
        BacnetApplicationTagObjectPropertyReference = 25,
        BacnetApplicationTagDestination = 26,
        BacnetApplicationTagRecipient = 27,
        BacnetApplicationTagCovSubscription = 28,
        BacnetApplicationTagCalendarEntry = 29,
        BacnetApplicationTagWeeklySchedule = 30,
        BacnetApplicationTagSpecialEvent = 31,
        BacnetApplicationTagReadAccessSpecification = 32,
        BacnetApplicationTagReadAccessResult = 33,
        BacnetApplicationTagLightingCommand = 34,
        BacnetApplicationTagContextSpecificDecoded = 35,
        BacnetApplicationTagContextSpecificEncoded = 36,
        BacnetApplicationTagLogRecord = 37
    }
}
